server:
  port: 80
  tomcat:
      max-http-post-size: -1
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/mybatisdb?serverTimezone=UTC&characterEncoding=utf-8
        username: root
        password: root

mybatis:
#  config-location: classpath:/mybatis-config.xml
  typeAliasesPackage: com.example.tkmybatis.entity
  mapperLocations: classpath:/mappings/**/*.xml

logging:
    level:
      com.example.tkmybatis.mapper: debug

